# -*- coding: utf-8 -*-
"""TSN-ml1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BikUcDiI-Mf32I-GoxlIsOI8gLwa9vOP
"""



"""addition of two numbers"""

a=int(input("enter the number"))
b=int(input("enter the number"))
c=a+b
print(c)

a=10
b=2
c=a*b
print(c)